"""
Django settings for savdopro project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# Maxfiy qiymatlar .env dan (gitga .env kirmaydi). settings.py kodi repo da qoladi.
SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY',
    'django-insecure-dev-only-set-DJANGO_SECRET_KEY-in-env',
)

DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', '*').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'core',
    'accounts',
    'shops',
    'subscriptions',
    'catalog',
    'inventory',
    'sales',
    'reports',
    'provider',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'accounts.middleware.UserLanguageMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'subscriptions.middleware.SubscriptionAccessMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        'CORS_ALLOWED_ORIGINS',
        'http://localhost:5173,http://127.0.0.1:5173',
    ).split(',')
    if origin.strip()
]

# Lokal tarmoqdagi har qanday qurilma (192.168.x.x, 10.x.x.x, 172.16-31.x.x)
# `5173` portdan kelsa ruxsat beramiz — telefondan test qilish uchun.
CORS_ALLOWED_ORIGIN_REGEXES = [
    r'^http://192\.168\.\d+\.\d+:5173$',
    r'^http://10\.\d+\.\d+\.\d+:5173$',
    r'^http://172\.(1[6-9]|2\d|3[0-1])\.\d+\.\d+:5173$',
]
CORS_ALLOW_CREDENTIALS = True

# Allow our custom tenant header (sent by the SPA on every request) through
# the CORS preflight. The default django-cors-headers list doesn't include it.
from corsheaders.defaults import default_headers as _default_cors_headers  # noqa: E402

CORS_ALLOW_HEADERS = list(_default_cors_headers) + [
    'x-organization-id',
]

ROOT_URLCONF = 'savdopro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'savdopro.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.postgresql'),
        'NAME': os.getenv('DB_NAME', 'savdopro'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'postgres'),
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': os.getenv('DB_PORT', '5432'),
        'OPTIONS': {
            'options': '-c timezone=Asia/Tashkent',
        },
    }
}


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'uz'

LANGUAGES = [
    ('uz', 'Uzbek'),
    ('ru', 'Russian'),
    ('en', 'English'),
]

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

# False: bazada PC/Toshkent soati (10:08) saqlanadi; True bo‘lsa UTC (+00) bo‘ladi.
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'accounts.User'

REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'core.uz_drf.uz_exception_handler',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/min',
        'user': '300/min',
        'otp': '5/min',
        'otp_verify': '10/min',
        'login': '10/min',
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
}

# SMS / messaging backend used by accounts.services.sms.send_sms().
# Override in production via the SMS_BACKEND env var or settings_local.py.
SMS_BACKEND = os.getenv(
    'SMS_BACKEND',
    'accounts.services.sms.ConsoleSmsBackend',
)
ESKIZ_EMAIL = os.getenv('ESKIZ_EMAIL', '')
ESKIZ_PASSWORD = os.getenv('ESKIZ_PASSWORD', '')
ESKIZ_FROM = os.getenv('ESKIZ_FROM', '4546')

# Auth security tuning.
AUTH_LOCKOUT_MAX_ATTEMPTS = int(os.getenv('AUTH_LOCKOUT_MAX_ATTEMPTS', '5'))
AUTH_LOCKOUT_MINUTES = int(os.getenv('AUTH_LOCKOUT_MINUTES', '15'))

# Stronger password policy for an SMS-verified, multi-tenant SaaS.
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'accounts.uz_password_validators.UzbekUserAttributeSimilarityValidator',
        'OPTIONS': {
            'user_attributes': ['phone', 'username', 'full_name', 'email'],
        },
    },
    {
        'NAME': 'accounts.uz_password_validators.UzbekMinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
    {
        'NAME': 'accounts.uz_password_validators.UzbekCommonPasswordValidator',
    },
    {
        'NAME': 'accounts.uz_password_validators.UzbekNumericPasswordValidator',
    },
]

# Lokal override: savdopro/settings_local.py (gitignore da)
try:
    from .settings_local import *  # noqa: F403
except ImportError:
    pass
