# Generated by Django 6.0.4 on 2026-05-18 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_debtor_client_uuid'),
        ('sales', '0004_sale_local_wall_clock'),
    ]

    operations = [
    ]
